name: Podo publish
on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: InstallDependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Run tests with secret key
        env:
          REACT_APP_BASE_URL: ${{secrets.REACT_APP_BASE_URL}}

      - name: publish Project
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PODO_WEB_KEY }}
          publish_dir: ./build
